---
- hosts: all
  become: yes
  gather_facts: yes

  pre_tasks:
    - name: Ensure Ansible dependencies are installed (DEBIAN 10).
      yum:
        name: libselinux-python
        state: present
      when:
        - ansible_os_family == 'Debian'
        - ansible_distribution_major_version | int == 10
 

  tasks:
    - name: Install Utilities.
      apt:
        name:
          - git
          - wget
          - curl
          - vim
        state: present
      when: ansible_os_family == 'Debian'
